// Honest root entry for `snappy` (the package `.` export).
//
// `index.js` is auto-generated by NAPI-RS and REWRITTEN on every `napi build`, so
// it stays the raw binding. On a native build that already includes
// `compressStream` / `uncompressStream`; on the wasm build those tokio-backed
// transforms are compiled out.
//
// This hand-written wrapper re-exports one-shot + class APIs and fills in
// honest stream fns (native or class-API polyfill) plus Node Duplex factories.

'use strict'

const binding = require('./index.js')
const { honestStreams } = require('./stream-polyfill.mjs')
const { createNodeStreamFactories } = require('./stream-polyfill.js')

const { compressStream, uncompressStream } = honestStreams(binding)
const { createCompressStream, createUncompressStream } = createNodeStreamFactories({
  compressStream,
  uncompressStream,
})

module.exports.compress = binding.compress
module.exports.compressSync = binding.compressSync
module.exports.uncompress = binding.uncompress
module.exports.uncompressSync = binding.uncompressSync
module.exports.Compressor = binding.Compressor
module.exports.Decompressor = binding.Decompressor
module.exports.compressStream = compressStream
module.exports.uncompressStream = uncompressStream
module.exports.createCompressStream = createCompressStream
module.exports.createUncompressStream = createUncompressStream
