/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function compress(input: string | Uint8Array, options?: EncOptions | undefined | null, signal?: AbortSignal | undefined | null): Promise<Buffer>

export declare function compressSync(input: string | Uint8Array, options?: EncOptions | undefined | null): Buffer

export interface DecOptions {
  asBuffer?: boolean
  /**
   * do not use `create_external_buffer` to create the output buffer \n
   * set this option to `true` will make the API slower \n
   * for compatibility with electron >= 21 \n
   * see https://www.electronjs.org/blog/v8-memory-cage and https://github.com/electron/electron/issues/35801#issuecomment-1261206333
   */
  copyOutputData?: boolean
}

export interface EncOptions {
  /**
   * do not use `create_external_buffer` to create the output buffer \n
   * for compatibility with electron >= 21 \n
   * set this option to `true` will make the API slower \n
   * see https://www.electronjs.org/blog/v8-memory-cage and https://github.com/electron/electron/issues/35801#issuecomment-1261206333
   */
  copyOutputData?: boolean
}

export declare function uncompress(input: string | Uint8Array, options?: DecOptions | undefined | null, signal?: AbortSignal | undefined | null): Promise<string | Buffer>

export declare function uncompressSync(input: string | Uint8Array, options?: DecOptions | undefined | null): string | Buffer
