name: Memory Leak Detect

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install
        uses: dtolnay/rust-toolchain@stable

      - name: 'Install dependencies'
        run: yarn install --mode=skip-build

      - name: 'Build binary'
        run: yarn build

      - name: 'Memory test'
        run: yarn test:mem
